# Generated by Django 4.2.3 on 2023-08-16 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermission',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 16)),
        ),
    ]
