# Generated by Django 4.2.3 on 2023-07-30 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_usermission_remove_completedmission_mission_and_more'),
        ('record', '0006_alter_mood_mission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompletedMission',
        ),
        migrations.AddField(
            model_name='usermission',
            name='mission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mission.mission'),
        ),
        migrations.AddField(
            model_name='usermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
