# Generated by Django 4.2.4 on 2023-08-23 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_alter_usermission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermission',
            name='date',
            field=models.DateField(default=datetime.date(2023, 8, 23)),
        ),
    ]
