# Generated by Django 3.2.20 on 2023-07-12 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='name',
        ),
    ]
