# Generated by Django 4.2.3 on 2023-08-16 06:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_alter_usermission_date'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2023, 8, 16)),
        ),
        migrations.AlterField(
            model_name='mood',
            name='missions',
            field=models.ManyToManyField(blank=True, null=True, to='mission.usermission'),
        ),
    ]
