# Generated by Django 4.2.3 on 2023-07-30 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mission', '0002_usermission_remove_completedmission_mission_and_more'),
        ('record', '0005_mood_mission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='mission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mission.usermission'),
        ),
    ]
